---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo1
spec:
  admin_user: admin
  admin_email: admin@localhost
  service_type: ClusterIP
  service_labels: |
    environment: dev
  ingress_type: route
  route_host: aws-demo.apps.dcmco.ocp.mvwc
  route_tls_termination_mechanism: Passthrough
  image: quay.io/ansible/awx
  image_version: "{{ image_version | default(omit) }}"
  image_pull_policy: IfNotPresent
  postgres_resource_requirements:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 4Gi
  postgres_storage_requirements:
    requests:
      storage: 8Gi
    limits:
      storage: 40Gi
  postgres_storage_class: thin
